---
version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.15
  docker: circleci/docker@1.6.0

executors:
  shellcheck:
    docker:
    - image: koalaman/shellcheck
  python:
    docker:
      - image: cimg/python:3.9
  hadolint:
    docker:
      - image: ghcr.io/hadolint/hadolint

jobs:
  flake8_lint:
    executor: python
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8
  docker_lint:
    dockerfiles: ./
    executor-class: medium
    hadolint-tag: 2.5.0-debian
    #ignore-rules: 'DL4005,DL3008'
    trusted-registries: 'docker.io'

workflows:
  version: 2
  scripts:
    jobs:
    - shellcheck/check
    - flake8_lint